version: '2.3'

services:
  worker:
    image: pcic/actions-runner:master
    container_name: actions-runner
    env_file:
      - ./envs/pdp.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /storage/data/projects/comp_support/gh_actions/:/storage/data/projects/comp_support/gh_actions/
      # Data mounts
      - /storage/data/climate/downscale:/storage/data/climate/downscale:ro
      - /storage/data/climate/hydrology:/storage/data/climate/hydrology:ro
      - /storage/data/climate/observations:/storage/data/climate/observations:ro
      - /storage/data/climate/PRISM:/storage/data/climate/PRISM:ro
      - /storage/data/projects/dataportal:/storage/data/projects/dataportal:ro
      - /storage/data/projects/hydrology:/storage/data/projects/hydrology:ro
      - /storage/data/projects/PRISM:/storage/data/projects/PRISM:ro

networks:
  default:
    external:
      name: pcicbr0
